name: package theme for distribution
on:
  push:
    branches: [ "raccoon" ]
  pull_request:
    branches: [ "raccoon" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: prepare layout
        run: |
          shopt -s extglob
          mkdir -p Themes/"Simply Love socks fork"
          mv * Themes/"Simply Love socks fork"
          mv Themes/"Simply Love socks fork"/extras/NoteSkins .
          rmdir Themes/"Simply Love socks fork"/extras

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: distributable
          path: .
          
