name: package theme for distribution
on:
  push:
    branches: [ "raccoon" ]
  pull_request:
    branches: [ "raccoon" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          path: checkout
        
      - name: get commit hash
        run: |
          cd checkout
          echo "short_hash=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_ENV
      
      - name: prepare layout
        run: |
          mkdir -p artifact/Themes/"Simply Love socks fork"
          mv checkout/* artifact/Themes/"Simply Love socks fork"

          sed -i 's/^Version=[^\r]*/& ${{ env.short_hash }}/' artifact/Themes/"Simply Love socks fork/ThemeInfo.ini"

          mv artifact/Themes/"Simply Love socks fork"/extras/NoteSkins artifact/
          rmdir artifact/Themes/"Simply Love socks fork"/extras

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SimplyLove-socks-${{ env.short_hash }}
          path: artifact/
