name: package theme for distribution
on:
  push:
    branches: [ "raccoon" ]
  pull_request:
    branches: [ "raccoon" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          path: checkout
      - name: prepare layout
        run: |
          mkdir -p artifact/Themes/"Simply Love socks fork"
          mv checkout/* artifact/Themes/"Simply Love socks fork"

          mv artifact/Themes/"Simply Love socks fork"/extras/NoteSkins artifact/
          rmdir artifact/Themes/"Simply Love socks fork"/extras

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SimplyLove-socks
          path: artifact/
